# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f83c41b9a2d24505f007bd1db1b1e7001765b8d5e86a013a6d438852d4e09ff0df6c344719cf85c0068e20c9874e1b147c36cede2e910df6d94ba2bf54237a27

test:
  secret_key_base: 3006ce88e2e870e3734ec3b576d3d77b3a80d22afbc09c5ed8692edd013a4bcfb9358be8bf35d81b711919d966fac3100239936caa18d6ee208a6bd5ad72d319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
